#应用程序的端口号和跟路径
server:
  port: 8080
  servlet:
    context-path: /api
#应用名称
spring:
  application:
    name: yun-picture-backend
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun_picture
    password: 123456
    username: root #这里一定要注意不是name（数据源名称）而是username！！！
#mybatisplus配置
mybatis-plus:
  configuration:
    #关闭下划线转驼峰功能
    map-underscore-to-camel-case: false
    #打印sql日志（只在开发环境开启）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 智能协同云图库接口文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.wyy.yunpicturebackend.controller